services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: studs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5555:5432"
    volumes:
      - .postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: